### ISSUE TITLE
Is keywordCloud no longer compatible with OJS 3.3?

### ISSUE THREAD

**Issue by luizbgomide** [lepidus/ojs3-keywordcloud-plugin#12]
I just updated to OJS 3.3 and the keyword cloud plugin is no longer available. Is it still compatible? Can it be manually installed?

**Comment by diegoabadan** [comment]
Our team will test and we will notify you here soon.

We will make it available in the OJS 3.3 plugin gallery as soon as we pass our tests.

**Comment by davidjb** [comment]
@luizbgomide With #11 in place, it's working in my install of 3.3.0_3.  I've manually installed it from Git, mind you.

**Comment by thiagolepidus** [comment]
@luizbgomide yes, the plugin is compatible with OJS 3.3
