### ISSUE TITLE
Lack of proper display of keywords in Persian

### ISSUE THREAD

**Issue by aliakbarsajjadi** [lepidus/ojs3-keywordcloud-plugin#15]
Hello, our journal site is bilingual.
 On the Persian page, the keywords are displayed in reverse in the keyword cloud.
 Persian is written from right to left, while in the keyword cloud, keywords are displayed from left to right like English language. 

Our journal site: 
Www.jupa.journal.af

![image](https://user-images.githubusercontent.com/85135755/122234835-70737180-ced2-11eb-9778-7cc939c0a233.png)

**Comment by diegoabadan** [comment]
Hi @aliakbarsajjadi 

Do you see it in the correct order at https://teste.ojs3.emnuvens.com.br/desenvolvimento/user/setLocale/fa_IR?source=%2Fdesenvolvimento ?

Can you test if with OJS Default Theme the problem still occurs? I asked you this on the PKP forum:
https://forum.pkp.sfu.ca/t/error-displaying-keyword-cloud/65081/9

Thank you and I hope we can come up with a solution.

**Comment by aliakbarsajjadi** [comment]
Hi Diego
  thanks for your attention.
  I talked to the magazine theme maker, they said the problem is with the plugin and not the theme.

**Comment by diegoabadan** [comment]
Thanks for the feedback.

We spent a few hours of our team, but we couldn't reproduce the problem in the official OJS theme.

Unfortunately, we are unable to support third-party themes. We hope you get help from its developer.
