### ISSUE TITLE
TypeError on getFileCache

### ISSUE THREAD

**Issue by thisnugroho** [lepidus/ojs3-keywordcloud-plugin#16]
TypeError when calling method getFileCache from class CacheManager which is referer to GenericCache, the problem is on third parameter (fallback) in getFileCache it's expect an callback function so when it's null,it's causes TypeError like the picture i attach.

![image](https://user-images.githubusercontent.com/49790011/132428776-2f6dfba3-1c0b-4c72-bc1e-941d071bfe15.png)

**Comment by diegoabadan** [comment]
The updated version can be found in the gallery.

Thanks for the collaboration!
