### ISSUE TITLE
Normalize upper & lowercase duplicated keywords

### ISSUE THREAD

**Issue by librariam** [lepidus/ojs3-keywordcloud-plugin#24]
Hi team!

I'm making this suggestion on behalf of a plugin user whose journal has both upper case and lower case keywords, creating duplication in the word cloud. They are wondering whether all keywords could be normalized to lowercase before inclusion in the plugin to avoid duplication. Thank you for considering!

OJS 3.3.0.8 / Plugin version 1.1.0.6

![image](https://github.com/lepidus/keywordCloud/assets/45104797/13d1fb5b-1385-4398-bc9e-5ec84f3e697d)

**Comment by diegoabadan** [comment]
Thanks @librariam !

We agree, we should soon release a version with normalization.

**Comment by thiagolepidus** [comment]
Hello @librariam

We made new versions of the plugin with duplicate removal and keyword normalization to lowercase.

Use the release [v1.1.1](https://github.com/lepidus/keywordCloud/releases/tag/v1.1.1) for OJS/OMP 3.3 and 3.2. The release [v2.0.1](https://github.com/lepidus/keywordCloud/releases/tag/v2.0.1) is for OJS/OMP 3.4.

The versions will soon be available in the gallery.

**Comment by librariam** [comment]
Amazing, thank you @thiagolepidus !
