### ISSUE TITLE
Display the keywords in the main language when absent

### ISSUE THREAD

**Issue by andre1mm** [lepidus/ojs3-keywordcloud-plugin#25]
When navigating in a language without registered keywords, the keyword cloud appears empty.

Display the keywords in the main language of the journal when there are no registered keywords in the selected navigation language.

**Comment by thiagolepidus** [comment]
Hi, @andre1mm.

We have released new versions adding this functionality.

- [v1.2.0](https://github.com/lepidus/keywordCloud/releases/tag/v1.2.0) to OJS/OMP 3.3.0 and 3.2.1
- [v2.1.0](https://github.com/lepidus/keywordCloud/releases/tag/v2.1.0) to OJS/OMP 3.4.0
