### ISSUE TITLE
Problem to view the keywords cloud block content - OJS 3.2.1.1.

### ISSUE THREAD

**Issue by edersotto** [lepidus/ojs3-keywordcloud-plugin#4]
Hello, I've installed the last version of the plugin on my OJS with version 3.2.1.1.

I can see the block, but it not showing any content.
I've tried find the problem on the php error log, but I only see warnings of the plugin as bellow.

I installed it through the .tar.gz package on https://github.com/lepidus/ojs3-keywordcloud-plugin/releases/download/v1.1.0/KeywordCloudBlockPlugin.tar.gz

My PHP version is 7.3

Please, can you help me about this?

Thank you!

[Mon Jun 29 11:38:55.510739 2020] [php7:warn] [pid 32256] [client 128.201.141.145:49787] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /var/www/interfacetecnologica/plugins/blocks/keywordCloud/KeywordCloudBlockPlugin.inc.php on line 93
[Mon Jun 29 11:38:55.510773 2020] [php7:warn] [pid 32256] [client 128.201.141.145:49787] PHP Warning:  array_count_values() expects parameter 1 to be array, null given in /var/www/interfacetecnologica/plugins/blocks/keywordCloud/KeywordCloudBlockPlugin.inc.php on line 97
[Mon Jun 29 11:38:55.510779 2020] [php7:warn] [pid 32256] [client 128.201.141.145:49787] PHP Warning:  arsort() expects parameter 1 to be array, null given in /var/www/interfacetecnologica/plugins/blocks/keywordCloud/KeywordCloudBlockPlugin.inc.php on line 98
[Mon Jun 29 11:38:55.510785 2020] [php7:warn] [pid 32256] [client 128.201.141.145:49787] PHP Warning:  array_slice() expects parameter 1 to be array, null given in /var/www/interfacetecnologica/plugins/blocks/keywordCloud/KeywordCloudBlockPlugin.inc.php on line 102
[Mon Jun 29 11:38:55.510789 2020] [php7:warn] [pid 32256] [client 128.201.141.145:49787] PHP Warning:  Invalid argument supplied for foreach() in /var/www/interfacetecnologica/plugins/blocks/keywordCloud/KeywordCloudBlockPlugin.inc.php on line 105

This is the home with the block, but no content

![image](https://user-images.githubusercontent.com/19962752/86001291-13428f80-b9e5-11ea-83d6-478b684a635a.png)

**Comment by martinmesa** [comment]
Hello,
I have the same problem, I have a new installation of ojs 3.2.1.1 and the plugin not show keywords

**Comment by edersotto** [comment]
> Hello,
> I have the same problem, I have a new installation of ojs 3.2.1.1 and the plugin not show keywords

Hello @martinmesa , I've found and fix the problem. 

@JhonathanLepidus , please, check this. I tried to make a pull request of my contribution, but it is not allowed. It's a fix to the problem on OJS3.2 that not show this plugin content.

To fix the error, replace the file "KeywordCloudBlockPlugin.inc.php" with the content in the file attached.

On OJS, this file is locate on "/plugins/blocks/keywordCloud".

Hope this helps you, as helped me.

[ojs3-keywordcloud-plugin.zip](https://github.com/lepidus/ojs3-keywordcloud-plugin/files/4848072/ojs3-keywordcloud-plugin.zip).

**Comment by martinmesa** [comment]
Hello @edersotto  thank you very much for your help. your solution works perfectly for me

**Comment by JhonathanLepidus** [comment]
Hello @edersotto 

I checked your contribution just now. It's correct, so I sent it in the last commit.

Thanks for your contribution!

**Comment by edersotto** [comment]
> Hello @edersotto
> 
> I checked your contribution just now. It's correct, so I sent it in the last commit.
> 
> Thanks for your contribution!

Hello @JhonathanLepidus , thank you!

**Comment by megabizland** [comment]
Hello guys,
I am using ojs  3.2.1.3 and having the same error. The kewordcloud is not displayed. The browse block also is not displayed. I have done as recommended above but not working. Please help.  Below is keywordcloud version i got from phpmyadmin.
![image](https://user-images.githubusercontent.com/65582246/106350089-2e280a00-630e-11eb-8dcb-390d64277426.png)

Thank you
