### ISSUE TITLE
Keywords showing all with same lenght

### ISSUE THREAD

**Issue by sergiobmartins** [lepidus/ojs3-keywordcloud-plugin#5]
Guys, thanks for the working in the plugin. I tried in my journal (version ojs-3.2.0-3) and now it's working, but I was expecting the words with more citations greater than the ones with less citation, but I'm seeing all with same lenght and some of them outside the box. Is there anything that I need to setup or it's such a bug? see the image below

![image](https://user-images.githubusercontent.com/39965334/87859324-c2022d80-c90a-11ea-8c9f-4b0c2446ce17.png)

PHP Version 7.2.24

**Comment by diegoabadan** [comment]
Thank you, @sergiobmartins. I will check with our team.

**Comment by sergiobmartins** [comment]
Hey guys, any update?

**Comment by DemilsonLepidus** [comment]
We made some changes to the way words are displayed, so that they are more distinguishable. You can find these changes in version v1.1.0.2

**Comment by diegoabadan** [comment]
As there was no return, I am closing. Please let me know if you think it has not yet been resolved.
