### ISSUE TITLE
Keywords Cloud not Visible

### ISSUE THREAD

**Issue by SamiullahSarwar** [lepidus/ojs3-keywordcloud-plugin#6]
Hi,

Using OJS 3.2.1.0 (https://brjournals.comsresearch.com/index.php/ijbs), I installed the keywordCloud-v1.1.0.1.tar.gz. Nevertheless, it displays the word "Keywords" and covers the space but keywords cloud is not visible. 
Looking forward to seeing the solution here. 

Regards,
Samiullah Sarwar

![image](https://user-images.githubusercontent.com/48204771/88488168-fe85f700-cfa4-11ea-91b7-59c75f0c809f.png)

**Comment by JhonathanLepidus** [comment]
Greetings

We made a new release of this plugin that could solve your problem. We ask you to install it and give us any news about it.

Regards,
Jhonathan Miranda

**Comment by diegoabadan** [comment]
As there was no return, I am closing. Please let me know if you think it has not yet been resolved.
