### ISSUE TITLE
Error na instalação plugin keywordcloud

### ISSUE THREAD

**Issue by Marciab902** [lepidus/ojs3-keywordcloud-plugin#7]
Olá

Qual o procedimento para desinstalar o plugin? Desde a tentativa de instalar não consigo visualizar e fica carregando infinitamente.

Versão ojs utilizada: 3.1.1.4

**Comment by diegoabadan** [comment]
Oi Marcia.

Removendo a pasta `ojs/plugins/blocks/keywordCloud` no servidor irá remover o plugin.

Para uma desinstalação completa, remova também da base:
`delete from versions where product = "keywordCloud"`
